### ISSUE TITLE
Add support ECDSA certificate generation

### ISSUE THREAD

**Issue by chinkung** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#376]
Currently JrCs/docker-letsencrypt-nginx-proxy-companion support only default RSA certificate generation.

It would be great if you could add support EC-256/EC-384 certificate generation.

**Comment by buchdag** [comment]
Hi. That's tied to the ACME client being used (simp_le) which does not support EC cert generation for now.

**Comment by Nottt** [comment]
Can you be more specific why this can't be done?

https://letsencrypt.org/docs/integration-guide/ < `Let’s Encrypt accepts RSA keys from 2048 to 4096 bits in length, and P-256 and P-384 ECDSA keys.`

**Comment by buchdag** [comment]
As told in my previous message we don't use certbot but simp_le.

**Comment by Nottt** [comment]
`https://github.com/Neilpang/acme.sh`. This seems to support it and be easy to use. 

Is there something I can do on my side to make you serve a ECC certificate? If I generate them outside of the container and replace it, something like that? 

Thanks!

**Comment by Nottt** [comment]
> I'm currently pretty much the only regular contributor to this project and I work on this on my free time, which I don't have much of.

I understand. Thanks for what you do, we really appreciate it :heart_eyes: 

I'm not good with nginx syntax at all, but I have experience with docker and bash so If that helps I can help you implement a better ACME client. Let me know. 

> Changing the client without breaking anything and maintaining downward compatibility is not a trivial task

My quick workaround I had in mind was just generating the ECC certificates outside of your container, and then overwriting the files.

**Comment by buchdag** [comment]
Woops sorry, forgot about the second message.

You can obtain your ECDSA certificates separately and use them with `nginx-proxy` without issue, you'll just have to follow [`nginx-proxy` doc for SSL support](https://github.com/jwilder/nginx-proxy#ssl-support).

> The contents of `/etc/nginx/certs` should contain the certificates and private keys for any virtual hosts in use. The certificate and keys should be named after the virtual host with a `.crt` and `.key` extension. For example, a container with `VIRTUAL_HOST=foo.bar.com` should have a `foo.bar.com.crt` and `foo.bar.com.key` file in the certs directory.

ECDSA is already enabled in the default cipher suite generated by `nginx.tmpl` so that should work out of the box.

On a side note, please be aware that the LE companion and `nginx-proxy` are two completely separate projects even if one is meant to work with the other. The two are maintained by different peoples, and I can't really handle `nginx-proxy` specific issue or assistance. The LE companion is pretty must "just" an automated ACME certificate manager. The actual proxying, nginx configuration, etc, that's on `nginx-proxy` side.

**Comment by buchdag** [comment]
[A version supporting ECDSA certificates generation is being worked on.](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319#issuecomment-452515417)
