### ISSUE TITLE
Incomplete cert creation

### ISSUE THREAD

**Issue by Eimuex** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#715]
I already generated couple of certs with these lines in wordpress months ago and everything is working fine:
```
-e VIRTUAL_HOST=domainname.com \
-e LETSENCRYPT_HOST=domainname.com \
-e LETSENCRYPT_EMAIL=email@address.com \
```
Now I tried to add one more site but in 'certs' folder it creates 'domain_name folder' with only account_key.json and account_reg.json files in it. 
I can access the site via HTTP so proxy is working, but when I enable https it breaks (500 Internal Server Error). When I review the cert from browser it looks like self signed cert. Showing only letsencrypt-nginx-proxy-companion tab without domain name. What could be the issue?

Thank you.

**Comment by buchdag** [comment]
Your cert isn't generated most probably because of an authorization issue.

Please check the docs : https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md

And the relevant issues : https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues?q=label%3A%22Failing+authorization%22+

**Comment by Eimuex** [comment]
AAAA record was pointing elsewhere. Thanks a bunch! This one is resolved.
