### ISSUE TITLE
Image not building or working on Raspbian stable, Amazon Linux 1 or 2, CentOS 7 or 8, Debian stable, Ubuntu 14.04 or earlier

### ISSUE THREAD

**Issue by peimansh** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#755]
When trying to build the image, the build fails with this error:
`Step 3/16 : RUN apk add --no-cache --virtual .build-deps         curl         gcc         git         make         musl-dev     && go get github.com/jwilder/docker-gen     && cd /go/src/github.com/jwilder/docker-gen     && git -c advice.detachedHead=false checkout $DOCKER_GEN_VERSION     && make get-deps     && make all     && go clean -cache     && mv docker-gen /usr/local/bin/     && rm -rf /go/src     && apk del .build-deps
 ---> Running in c83e21a5883b
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
  curl (no such package):
    required by: .build-deps-19700101.000000[curl]
  gcc (no such package):
    required by: .build-deps-19700101.000000[gcc]
  git (no such package):
    required by: .build-deps-19700101.000000[git]
  make (no such package):
    required by: .build-deps-19700101.000000[make]
  musl-dev (no such package):
    required by: .build-deps-19700101.000000[musl-dev]
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
ERROR: unable to select packages:
The command '/bin/sh -c apk add --no-cache --virtual .build-deps         curl         gcc         git         make         musl-dev     && go get github.com/jwilder/docker-gen     && cd /go/src/github.com/jwilder/docker-gen     && git -c advice.detachedHead=false checkout $DOCKER_GEN_VERSION     && make get-deps     && make all     && go clean -cache     && mv docker-gen /usr/local/bin/     && rm -rf /go/src     && apk del .build-deps' returned a non-zero code: 6
ERROR: Service 'nginx-proxy-letsencrypt' failed to build`

I even tried to use the previous 1.x version with "simple.sh" but seems to still fail:

`Step 3/15 : RUN apk add --update         curl         gcc         git         make         musl-dev
 ---> Running in 5e45349e844a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
ERROR: unable to select packages:
  curl (no such package):
    required by: world[curl]
  gcc (no such package):
    required by: world[gcc]
  git (no such package):
    required by: world[git]
  make (no such package):
    required by: world[make]
  musl-dev (no such package):
    required by: world[musl-dev]
The command '/bin/sh -c apk add --update         curl         gcc         git         make         musl-dev' returned a non-zero code: 5
ERROR: Service 'nginx-proxy-letsencrypt' failed to build`

The image has been already built and worked on my RPi 2 months ago, but I cleared Docker cache to save some space. But now without making any changes to the Dockerfile or the code, I'm getting these errors.

**Comment by peimansh** [comment]
It's related to a network issue with alpine 3.13 :
https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-778776314

**Comment by buchdag** [comment]
Hi. Could you please follow the repository's bug template ?

Bug description
-----------------
A clear and concise description of what the bug is.

letsencrypt-nginx-proxy-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```bash
[you@yourhost]: $ docker logs companion-container-name
Info: running letsencrypt-nginx-proxy-companion version v2.0.0
[...]
```

If this first log line isn't present you are using a `v1` image: please provide the [tagged version](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/releases) you are using. If you are using `latest`, please try again with a tagged release before opening an issue (the last `v1` tagged release is `v1.13.1`).

nginx-proxy-companion configuration
-----------------

Please provide the configuration (either command line, compose file, or other) of your nginx-proxy stack and your proxied container(s).

You can obfuscate information you want to keep private (and should obfuscate configuration secrets) such as domain(s) and/or email adress(es), but other than that **please provide the full configurations** and not the just snippets of the parts that seem relevants to you.

Containers logs
-----------------

Please provide the logs of:
- your `letsencrypt-nginx-proxy-companion` container
- your `nginx-proxy` container (or `nginx` and `docker-gen` container in a three containers setup)

`docker logs name-of-the-container`

Docker host
-----------------

 - OS: [e.g. Ubuntu 20.04]
 - Docker version: output of `docker version`

**Comment by buchdag** [comment]
@peimansh is this still an issue ?

**Comment by peimansh** [comment]
@buchdag Yes.
The workaround at the moment was to downgrade and force use alpine-3.12 and the problem was fixed but it still doesn't work on alpine-3.13

**Comment by buchdag** [comment]
I'll be honest, I don't entirely get the issue at hand here, our `arm/v7` images [still build fine on GitHub Actions with Docker buildx and are pushed to Dockerhub](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/runs/2009048039?check_suite_focus=true). Does this happen only when you try to build the image locally on a an `arm/v7` host ?

**Comment by buchdag** [comment]
That does not seem to be something that will be fixed on Alpine's end :

> Therefore, the following platforms are not suitable as Docker hosts for 32-bit Alpine Linux 3.13.0, due to containing out-of-date libseccomp: Amazon Linux 1 or 2, CentOS 7 or 8, Debian stable without debian-backports, **Raspbian stable**, Ubuntu 14.04 or earlier, and Windows. This applies regardless of whether the Linux distribution Docker packages or separate Docker package repositories are used.

**Comment by buchdag** [comment]
@peimansh I took the liberty of changing your issue title to something more generic for people hitting the same problem on other distros that use an outdated `libseccomp`.

The recommended workaround for now would be either :
- follow the instructions in https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
- use https://github.com/buchdag/multiarch-letsencrypt-nginx-proxy

I'm closing this issue as there isn't a lot more we'll be able to do.

**Comment by buchdag** [comment]
@nickwest has a manual solution to this in the `alpinelinux/docker-alpine`'s issue : https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-812287338
